stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: python:buster
  script:
    - echo "Running tests"
    - cd docker-flask-app
    - pip install -r requirements.txt
    - py.test tests/

build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/hat_player:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
