stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: python:buster
  script:
    - echo "Running tests"
    - cd docker-flask-app
    - pip install -r requirements.txt
    - py.test tests/

build:
  stage: build
  script: echo "Building the app"
